#!/bin/bash
#
# joia deploys an app to an instance on AWS

conf=".joia.sh"

# Override environment if there's a .env
[ -f ".env" ] && source ".env"

# Defaults
[ ! "$AMI" ] && AMI=ami-fce3c696 # ubuntu 14.04
[ ! "$APP_DIR" ] && APP_DIR=app
[ ! "$INSTANCE_TYPE" ] && INSTANCE_TYPE=t2.nano
[ ! "$INSTANCE_USER" ] && INSTANCE_USER=ubuntu

#
# Helper functions

instance_check () {
  [ ! "$INSTANCE_ID" ] && echo "No reference found for INSTANCE_ID" && exit 1
}

update_env () {
  # Replace value if ed exists and var in file
  hash ed 2>/dev/null && ed_out="$(ed -s .env <<EOF
g/^$1=/s/=.*/=$2
w
EOF
)"

  # Otherwise just append the var to the file
  [ ! "$ed_out" ] && echo "$1=$2" >> .env
}

#
# Command functions

joia_deploy () {
  echo "A joia_deploy function must be defined in $conf"
}

joia_down () {
  read -p "Terminate instance $INSTANCE_ID? (Enter \"y\" to proceed.) " terminate_yes
  [ ! "$terminate_yes" = "y" ] && exit 0

  echo "Instance $INSTANCE_ID terminating"
  aws ec2 terminate-instances --instance-ids "$INSTANCE_ID" > /dev/null

  update_env "INSTANCE_ID" ""
  update_env "INSTANCE_HOSTNAME" ""
}

joia_host () {
  echo "Getting hostname"
  INSTANCE_HOSTNAME=$(aws ec2 describe-instances --instance-ids "$INSTANCE_ID" \
    --query 'Reservations[0].Instances[0].PublicDnsName' | tr -d '"')

  if [ ! "$INSTANCE_HOSTNAME" ]; then
    >&2 echo "No hostname returned for $INSTANCE_ID"
    return 1
  fi

  update_env "INSTANCE_HOSTNAME" "$INSTANCE_HOSTNAME"
  ssh-keyscan "$INSTANCE_HOSTNAME" >> ~/.ssh/known_hosts 2> /dev/null
}

joia_install () {
  echo "A joia_install function must be defined in $conf"
}

joia_pull () {
  rsync -e "ssh -i $HOME/.ssh/$KEY_PAIR.pem" -zrptui --delete --exclude=".git" "$INSTANCE_USER@$INSTANCE_HOSTNAME:$APP_DIR/" ./
}

joia_push () {
  rsync -e "ssh -i $HOME/.ssh/$KEY_PAIR.pem" -zrptui --delete --exclude=".git" ./ "$INSTANCE_USER@$INSTANCE_HOSTNAME:$APP_DIR/"
}

joia_ssh () {
  cmd="$1"
  [ "$cmd" ] || cmd="bash --login"
  ssh -i "$HOME/.ssh/$KEY_PAIR.pem" "$INSTANCE_USER@$INSTANCE_HOSTNAME" -t "cd $APP_DIR; $cmd"
}

joia_sync () {
  unison -terse -batch -prefer newer -ignore "Path .git" -sshargs "-i $HOME/.ssh/$KEY_PAIR.pem" . "ssh://$INSTANCE_USER@$INSTANCE_HOSTNAME/$APP_DIR"
}

joia_up () {
  if [ "$INSTANCE_ID" ]; then
    echo "Existing reference found: INSTANCE_ID=$INSTANCE_ID"
    read -p "Spin up new instance and replace reference? (Enter \"y\" to proceed.) " ref_replace
    [ ! "$ref_replace" = "y" ] && exit 0
  fi

  echo "Provisioning instance"
  INSTANCE_ID=$(aws ec2 run-instances --key-name "$KEY_PAIR" --instance-type "$INSTANCE_TYPE" \
    --associate-public-ip-address --image-id "$AMI" --subnet-id "$SUBNET" \
    --query 'Instances[0].InstanceId' | tr -d '"')

  if [ "$INSTANCE_NAME" ]; then
    echo "Tagging instance"
    aws ec2 create-tags --resources "$INSTANCE_ID" --tags "Key=Name,Value=$INSTANCE_NAME"
  fi

  update_env "INSTANCE_ID" "$INSTANCE_ID"

  echo "Waiting for instance $INSTANCE_ID to come online (this may take a few minutes)"
  aws ec2 wait instance-status-ok --instance-ids "$INSTANCE_ID"

  joia_host
  joia_push
  joia_install
  joia_deploy

  echo "Sync and deploy on changes with \"joia watch\""
}

joia_watch () {
  echo "Syncing and deploying on file changes"
  while true; do
    # Only run deploy on output from sync
    # (since files have been updated on the instance)
    sync_out="$(joia_sync 2>&1)"
    if [ "$sync_out" ]; then
      echo "$sync_out"
      joia_deploy
    fi
    sleep 5
  done
}

# Overwrite functions with those defined in $conf
[ -f "$conf" ] && source "$conf"

case "$1" in
  deploy)
    instance_check
    joia_deploy
    ;;
  down)
    instance_check
    joia_down
    ;;
  host)
    instance_check
    joia_host
    ;;
  install)
    instance_check
    joia_install
    ;;
  pull)
    instance_check
    joia_pull
    ;;
  push)
    instance_check
    joia_push
    ;;
  ssh)
    instance_check
    shift
    joia_ssh "$@"
    ;;
  sync)
    instance_check
    joia_sync
    ;;
  up)
    # instance check handled in joia_up
    joia_up
    ;;
  watch)
    instance_check
    joia_watch
    ;;
  *)
    cat <<EOF
usage: joia <command>

commands:
  deploy    deploy app on instance
  down      destroy instance
  host      set up ssh host config for an instance
  install   install app stack on instance
  push      push files to instance
  pull      pull files from instance
  ssh       ssh into instance
  sync      sync files with instance
  up        spin instance up
  watch     sync and deploy on file changes
EOF
    exit 1
esac
